name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '35 11 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'No activity on this issue, marking as stale.'
        stale-pr-message: 'No activity on this pull request, marking as stale.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
